fix maven wrapper run error by recreating it
recreate maven wrapper by command:

command mvn -N io.takari:maven:0.7.7:wrapper -Dmaven=3.5.2

info about maven wrapper creator:

- https://github.com/takari/maven-wrapper
- https://mvnrepository.com/artifact/io.takari/maven

below is maven wrapper run error info:

./mvnw -v
Running version check
The found version is [${revision}]
Deactivating "milestone" profile for version="${revision}"
Deactivating "central" profile for version="${revision}"
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain